### ISSUE TITLE
Errors "Spec with full name: SPEC_NAME not found' when using describe

### ISSUE THREAD

**Issue by ArnaudBuchholz** [SAP/ui5-uiveri5#198]
It looks like only one describe is allowed in a spec and it must match the spec name (without .spec.js). Any reason for this limitation ?

**Comment by maximnaidenov** [comment]
Hi Arnaud,
this is a known, documented limitation. The reason was the initial design of the visual testing feature where we needed to resolve the name of the control and we implemented it in the simplest possible way that posed this limitation. We are in the process of reworking our protractor integration and in this context, we plan to remove this limitation.

**Comment by ArnaudBuchholz** [comment]
Perfect, thx !

**Comment by vladgovoreanu** [comment]
WHERE HAS THIS LIMITATION BEEN DOCUMENTED ? I spent weeks trying to figure out what was wrong with my setup and there is no reference of this stupid limitation.

**Comment by tsaleksandrova** [comment]
here https://github.com/SAP/ui5-uiveri5/blob/master/docs/issues.md#failed-spec-with-full-name-spec-name-not-found

**Comment by maximnaidenov** [comment]
We are working on lifting this limitation, there is already a PR and we will merge shortly.
