### ISSUE TITLE
Stable test while refreshing a page

### ISSUE THREAD

**Issue by urigeva93** [SAP/ui5-uiveri5#23]
Hi,

In a part of my test, I try to change the language of my site and as a result the page needs to be refreshed. When I do that, I get the following error:

![veri5_error](https://user-images.githubusercontent.com/24360791/52934996-c9fa1e80-3360-11e9-91b1-bf876e8b873c.PNG)

I tried some workarounds, but the best solution I found till now is too isolate this particular check in a different test (and then the error disappears).

Thanks

**Comment by maximnaidenov** [comment]
Hi Uri,
the root cause for this error is the page reloading.  UI5 is intended to be used in SPAs where you never reload the page and every UI change happens over data binding. So uiveri5 does not support page reloading by design. But it seems hybrid applications are more widespread than we anticipated so we have the page reloading feature in our backlog.

**Comment by saard** [comment]
Thanks @maximnaidenov  we also have this requirement when we have to switch between tabs and check the result.

**Comment by maximnaidenov** [comment]
Hi, we just release a version that supports browser refresh: https://github.com/SAP/ui5-uiveri5/releases/tag/v1.39.0 Please check the docs, try it and please create an issue if you face problems.
