### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by LachlanStephan** [SAP/ui5-uiveri5#334]
Hi there, we are currently having some trouble with handling errors within the test scripts. For example when I run the below test you can see the pop-up error that is returned after clicking onto a new page. Although this error is present the test will pass. 

Currently the click to the broken page is the last function in this test script and I assume it passes because all functions were completed. However, when I add an extra step to the test after clicking on the page it will try to execute that step and not acknowledge the error.

My question is, is there any way to have tests break and return as failed if an error like this shows or do I need to rely on the expect function to know whether a test has passed or failed and manually check for errors? I would like to have the tests break as soon as the error shows and potentially return the error message.

Any help is much appreciated, thanks in advance! 

![image](https://user-images.githubusercontent.com/70623086/128665325-772667d6-702d-403f-82cb-63ac6062a29f.png)

![image](https://user-images.githubusercontent.com/70623086/128665451-d7a6fb46-46f1-4741-ab21-f2ad10ea72ff.png)

**Comment by maximnaidenov** [comment]
Hi,
you should start with the correct mindset - the test is a CODE that drives the browser and simulate user actions. There is no magic, the test could not guess what the app is supposes to do and somehow tell you there is an error. Looking at the log, there is NO SINGLE EXPECTATION in your test so this is like a bling person running the test - no way to see the error. And obviously the scenario is so simple that it passes even with broken app. 
In a real test, this can't happen because the app state won't match the expected one in the test and so the test will fail with some error - missing element on the screen, etc.

**Comment by LachlanStephan** [comment]
Hey thanks for the response. 

I left out the expectation on purpose to see if I could catch the error itself. But that answers that. Cheers
