### ISSUE TITLE
UIVeri5 uses old chromedriver version

### ISSUE THREAD

**Issue by cvakiitho** [SAP/ui5-uiveri5#34]
Due to weird, to say the least, change in chromedriver naming conventions:
https://sites.google.com/a/chromium.org/chromedriver/downloads/version-selection 

UIVeri5 now uses 2.46 chromedriver instead of 73+ , this completely breaks running in linux/mac environment, without manual chromedriver update. 

To fix this we'd have to check chrome version before downloading chromedriver :/

**Comment by cvakiitho** [comment]
discussion/bug report: https://groups.google.com/forum/#!topic/chromedriver-users/8VmMaFjs1cg seems, that it might get resolved automatically "in a few month", but it seems that even chromedriver team is not consistent on it.

**Comment by maximnaidenov** [comment]
Hi Tomas,
We recognized this problem last week, will provide a fix ASAP (till next week), meanwhile you could workaround it with a soft link to a chromedriver-2.46, this will disable the chromedriver download.

**Comment by maximnaidenov** [comment]
uff, they effectively disabled the "latest" mechanism as the chromedriver is now versioned for the browser and we could not download the highest version. Other browsers like Edge and Safari use similar version model but package the webdriver with the browsers so effectively you always get the correct version. The solution would need to be more complex. The problem is that I do not see a reliable way to download the respective webdriver automatically. Do you have idea how to handle this ?

**Comment by maximnaidenov** [comment]
@cvakiitho 
Another workaround is to manually force a specific version of chromedriver as explained in the first chapter: https://github.com/SAP/ui5-uiveri5/blob/master/docs/config/drivers.md

**Comment by cvakiitho** [comment]
Yeah I know, I tried to lobby against the change: https://groups.google.com/forum/#!topic/chromedriver-users/8VmMaFjs1cg

apart from having hardcoded latest version in this repo, I can think of only checking actual chrome version via --version from command line, but that's platform dependent.

I'll dig a bit more tomorrow.

**Comment by maximnaidenov** [comment]
I also was thinking of checking chrome version but the problem is starting chrome as this is platform specific e.g. we need to hardcode all the (non-trival) logic in our code. Another solution I am evaluating is having a source of truth in the form of a file in his repo. We will update it with the release version of the current stable version of chrome and uiveri5 will check on every start, instead of checking the chromedriver repo. We could even keep the versions per channel e.g. you configure the chrome channel you use and uiveri5 will update the chromedriver respectively.

**Comment by cvakiitho** [comment]
well, least work would probably be, to just hardcode major version to this repo: 
https://chromedriver.storage.googleapis.com/LATEST_RELEASE_74
instead of LATEST_RELEASE, as major version changes like once in ~3 months.

**Comment by maximnaidenov** [comment]
and then what, in 3 months you would need to update to a new uiveri5 version?.  This is a nightmare, we have seen it first hand as many developers will miss understanding what is the problem and will write an issue/ticket/complain that our tool does not work.

**Comment by cvakiitho** [comment]
Yeah I know, but we have three options anyway, hardcode the major version somewhere, check actual installed chrome version(best imo), or leave chromedriver installation to everyone, as every other testing framework is doing :)

**Comment by maximnaidenov** [comment]
Actually, I am thinking of a fourth option - hardcode in some central file and make uiveri5 check it on every start. This way you will get updates of chromedriver without a module update.

**Comment by cvakiitho** [comment]
Yeah, that way we won't have to change anything apart from link to LATEST_RELEASE check. , I like it.

**Comment by cvakiitho** [comment]
We can easily use gh-pages to generate LATEST_RELEASE url hosted by ghub: 
SAP/ui5-uiveri5#37

**Comment by cvakiitho** [comment]
btw, latest chromedriver needs latest selenium webdriver standalone https://github.com/cvakiitho/ui5-uiveri5/commit/291de448b8accd6f83be2a4eb5a1424ccdaf1fd7

**Comment by maximnaidenov** [comment]
Hi, we delivered the fix we discussed here: https://github.com/SAP/ui5-uiveri5/releases/tag/v1.37.0
