### ISSUE TITLE
Error message in pipeline: WebDriverError: invalid session id

### ISSUE THREAD

**Issue by tamiarah** [SAP/ui5-uiveri5#378]
Hi!

We also have since last week Friday an issue with the UIVeri5 tests in our pipeline, although there were no changes in the settings:

error uiVeri5ExecuteTests - ERROR: Error while taking report screenshot: WebDriverError: invalid session id
info  uiVeri5ExecuteTests - Build info: version: '4.7.0', revision: '52e3a49ea2'
info  uiVeri5ExecuteTests - System info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.10.127+', java.version: '11.0.17'
info  uiVeri5ExecuteTests - Driver info: driver.version: unknown

Locally everything is working fine, only the pipeline has issues here with executing the tests.

UI5 version is: @ui5/uiveri5 v1.47.9
Chrome version: chrome=108.0.5359.71
Chrome driver version:108.0.5359.71

Do you have any hints how to solve this error?
Thanks in advance!

Best regards,
Christina

**Comment by hmanchev** [comment]
Hello, could you please give more details on your infrastructure? How your chromedriver is configure? Is it locally started on you have remote communication like browser cloud?
Also log with -v parameter (verbose) will be useful.

From the stack you sent, I can see that maybe the webdriver session is already closed, but the reason is not clear for now.

**Comment by tamiarah** [comment]
Hi! Sorry, I just found out, that we have the same error like in #377. 
We will try the proposed solution you gave in this issue.

**Comment by zyhmichelle** [comment]
Hello @tamiarah may I ask whether you have solved the issue? Our team are also facing the same issue with you.

**Comment by hmanchev** [comment]
I suppose that you use piper too, right? 
There are several requests for similar issues from teams using piper and it seems that the reason is insufficient resources in the executor containers.

If you are able to execute locally (on your machine) the UIVeri5 scenarios successfully, so I would suggest to contact Piper  colleagues and to ask for more resources in the containers.

**Comment by tamiarah** [comment]
Yes, we use Piper too. Thanks for your help @hmanchev!

@zyhmichelle : Currently we have not solved it, but somebody else already created a ticket for the piper teams.
We will now wait for their response.
